name: build java

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: setting JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: find . -type f -name "*.java" > sources.txt
      - run: javac @sources.txt